# Deployment Section
deployment:
  namespace: dunia-belanja
  replicaCount: 1
  containers:
    ports: 80
    image:
      repository: 211104/api
      tag: v-daa4f13

# Service Section
service:
  port: 80
  targetPort: 9000
  protocol: TCP

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {} 

# Ingress Section
ingress:
  enabled: false
  # annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # hosts:
  #   - host: chart-example.local
  #     paths:
  #       - path: /
  #         pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# ConfigMap Section
configMap:
  data:
    .env: |
      APP_NAME=DuniaBelanja
      APP_ENV=local
      APP_KEY=base64:1itA+7ics9KziMGIKfJbiiqlaOX6sKO16PC5bQ6LTPA=
      APP_DEBUG=true
      APP_URL=https://api-duniabelanja.krobot.my.id
      WEB_URL=https://duniabelanja.krobot.my.id

      LOG_CHANNEL=stack
      LOG_DEPRECATIONS_CHANNEL=null
      LOG_LEVEL=debug

      DB_CONNECTION=mysql
      DB_HOST=dunia-belanja-db-mysql.dunia-belanja.svc.cluster.local
      DB_PORT=3306
      DB_DATABASE=dunia_belanja
      DB_USERNAME=dev-aselab
      DB_PASSWORD=benhilbanjir12345

      BROADCAST_DRIVER=log
      CACHE_DRIVER=file
      FILESYSTEM_DISK=local
      QUEUE_CONNECTION=sync
      SESSION_DRIVER=file
      SESSION_LIFETIME=120

      MEMCACHED_HOST=127.0.0.1

      REDIS_HOST=127.0.0.1
      REDIS_PASSWORD=null
      REDIS_PORT=6379

      MAIL_MAILER=smtp
      MAIL_HOST=mailpit
      MAIL_PORT=1025
      MAIL_USERNAME=null
      MAIL_PASSWORD=null
      MAIL_ENCRYPTION=null
      MAIL_FROM_ADDRESS="hello@example.com"
      MAIL_FROM_NAME="${APP_NAME}"

      AWS_ACCESS_KEY_ID=
      AWS_SECRET_ACCESS_KEY=
      AWS_DEFAULT_REGION=us-east-1
      AWS_BUCKET=
      AWS_USE_PATH_STYLE_ENDPOINT=false

      PUSHER_APP_ID=
      PUSHER_APP_KEY=
      PUSHER_APP_SECRET=
      PUSHER_HOST=
      PUSHER_PORT=443
      PUSHER_SCHEME=https
      PUSHER_APP_CLUSTER=mt1

      VITE_APP_NAME="${APP_NAME}"
      VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
      VITE_PUSHER_HOST="${PUSHER_HOST}"
      VITE_PUSHER_PORT="${PUSHER_PORT}"
      VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
      VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

      XENDIT_KEY_DEV=xnd_development_eX7bxJUCnHbNDh8wThQ8pBPvOA0JlFVcEjg4bomNcSDMKmc7CTVaUEmBSz
      XENDIT_KEY_PROD=xnd_development_eX7bxJUCnHbNDh8wThQ8pBPvOA0JlFVcEjg4bomNcSDMKmc7CTVaUEmBSz
      XENDIT_TOKEN_CALLBACK_DEV=Gf27GoZlFl2PRCNOfBuiSxCxO4pTipKe7yImEFMt4YtN1LCt
      XENDIT_TOKEN_CALLBACK_PROD=Gf27GoZlFl2PRCNOfBuiSxCxO4pTipKe7yImEFMt4YtN1LCt

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# autoscaling:
  # enabled: false
  # minReplicas: 1
  # maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}