name: Gitops-CI
on: 
  push:
    tags:
    - 'k8s-v*-helm*'

jobs: 
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api:${{ github.ref_name }}
  
  deploy_helm:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Deploy Helm
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        with:
          args: |
            helm repo add api-charts https://${{ github.token }}@raw.githubusercontent.com/RPLGDC-1/helm-chart-api/main/
            helm upgrade --install api-charts api-charts/api-charts -f ./values.yaml --set deployment.containers.image.tag=${{ github.ref_name }} -n dunia-belanja
