name: Gitops-CI
on: 
  push:
    tags:
      - 'k8s-v*-helm*'

jobs: 
  # build:
  #   name: build
  #   runs-on: ubuntu-latest
    
  #   outputs:
  #     output_sha: ${{ steps.sha.outputs.short_sha}}

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v2

  #     - name: Login to docker
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
      
  #     - name: Get short of git commit hash
  #       id: sha
  #       run: |
  #         git_hash=$(git describe --match 'v[0-9]*' --tags --always)
  #         echo "::set-output name=short_sha::$git_hash"
      
  #     - name: Print short commit sha
  #       run: echo ${{ steps.sha.outputs.short_sha }}
      
  #     - name: Build and push docker image
  #       uses: docker/build-push-action@v4
  #       with:
  #         push: true
  #         tags: ${{ secrets.DOCKERHUB_USERNAME }}/api:v-${{ steps.sha.outputs.short_sha }}
  
  deploy_helm:
    name: deploy
    runs-on: ubuntu-latest
    # needs: build
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Install helm 3
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
      
      - name: Add to repo
        run: |
          helm repo add api-charts ${{ secrets.REPO_URL }}
          helm repo update

      - name: Deploy helm
        run: |
          helm upgrade --install api-charts api-charts/api-charts --set deployment.containers.image.tag=v-daa4f13 --values ./values.yaml -n dunia-belanja

