name: Gitops-CI
on: 
  push:
    branches:
      - feature/continous-integration

jobs: 
  build:
    name: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api:v0.0.${{ github.run_number }}
          push: true
          file: ./depolyments/Dockerfile

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: 'RPLGDC-1/api'
          token: ${{ secrets.PAT }}

      - name: Setup git
        run: |
          git config user.email "yazid.al2418@gmail.com"
          git config user.name "Yazid Al Ghozali"
      
      - name: Update deployment
        run: |
          pwd
          cd ./deployments
          ls
          cat deployment.yaml
          sed -i 's|image: 211104/api:v0.0.13|image: 211104/api:v0.0.${{github.run_number}}|' deployment.yaml  
          cat deployment.yaml
          git status
      
      - name: Auto commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply latest deployment with manifest ${{ github.run_number }}
          branch: feature/continous-integration