name: Gitops-CI
on: 
  push:
    branches: [main]
  pull_request_review:
    types:
      - submitted

jobs: 
  build:
    name: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get short of git commit hash
        id: sha
        run: |
          git_hash=$(git rev-parse --short ${{ github.sha }})
          echo "::set-output name=short_sha::$git_hash"
      
      - name: Print short commit sha
        run: echo ${{ steps.sha.outputs.short_sha }}
      
      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api:v-${{ steps.sha.outputs.short_sha }}
  
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: 'RPLGDC-1/infra-api'
          token: ${{ secrets.PAT }}

      - name: Setup git
        run: |
          git config user.email "yazid.al2418@gmail.com"
          git config user.name "Yazid Al Ghozali"
          echo ${{ github.sha }}
      
      - name: Update deployment
        run: |
          sed -i 's|image: ${{ secrets.DOCKERHUB_USERAME }}/api:\(v0.0.[0-9]*\)|image: ${{ secrets.DOCKERHUB_USERAME }}/api:v-${{ steps.sha.outputs.short_sha }}|' deployment.yaml  
          cat deployment.yaml
          git status
          git add .
          git commit -m "Update image with version: v-${{ steps.sha.outputs.short_sha }}"
          echo ${{ github }}
      - run: git push origin main