name: Gitops-CI
on: 
  push:
    branches:
      - main

jobs: 
  build:
    name: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/api
          tags: v${{ github.run_number }}
          file: ./deployments/Dockerfile
          context: .

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Modify image
        run: |
          git config user.email "yazid.al2418@gmail.com"
          git config user.name "Yazid Al Ghozali"
          pwd
          cd ./deployments
          ls
          cat deployment.yaml
          sed -i "s+211104/api:v0.0.6+211104/api:app-$RUN_NUMBER+g" deployment.yaml
          cat deployment.yaml
          git add .
          git commit -m "Done  by Github Actions   Job changemanifest: ${{ github.run_number }}"
          git push origin main
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          RUN_NUMBER: ${{ github.run_number }}



      