name: Gitops-CI
on: 
  push:
    branches:
      - main

jobs: 
  build:
    name: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/api
          tags: v0.0.${{ github.run_number }}
          file: ./deployments/Dockerfile
          context: .

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: 'RPLGDC-1/api'
          token: ${{ secrets.PAT }}

      - name: Setup git
        run: |
          git config user.email "yazid.al2418@gmail.com"
          git config user.name "Yazid Al Ghozali"
      
      - name: Update deployment
        run: |
          pwd
          cd ./deployments
          ls
          cat deployment.yaml
          sed -i "s+211104/api:v0.0.6+211104/api:v0.0.${{ github.run_number }}+g" deployment.yaml
          cat deployment.yaml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update deployment with manifest image version -> ${{ github.run_number }}
          branch: main